name: my-pipeline
on: 
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: list build-files
        run: ls